# 1.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

## Часть 1 (19 баллов)

1) Импортировать numpy и написать версию (1 балл)

In [0]:
import numpy as np

In [0]:
numpy.version.version

'1.16.5'

2) Создать нулевой вектор размера 10 (1 балл)

In [0]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7 (2 балла)


In [0]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100 включительно (2 балла)

In [0]:
np.arange(10,101,2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд (4 балла)

In [0]:
np.random.random(15)[::-1]

array([0.73511529, 0.43374869, 0.56038763, 0.48631319, 0.42525817,
       0.4945572 , 0.05767311, 0.68556282, 0.20371541, 0.66405757,
       0.77645955, 0.29561952, 0.05999219, 0.62436556, 0.35068031])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9 (4 балла)

In [0]:
np.arange(0,9,1).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх. (5 баллов)

In [0]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## Часть 2 (26 баллов)

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки. (2 балла)

In [0]:
matr = np.full((4,4),7)
for i in range(1,matr.shape[0]+1):
  matr[i-1,i-1] = i
print(matr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках. (2 балла)

In [0]:
matr = np.zeros((5,5))
for i in range(0, matr.shape[0]):
  for j in range(0, matr.shape[0]):
    matr[i,j] = j
matr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки (3 балла)

In [0]:
a = np.random.random((10,10))
b = np.mean(a[:,:10], axis = 1)
c = np.zeros((10,10))
for i in range(0,10):
  c[i,:] = a[i,:] - b[i]
print(c)

[[ 0.37211534 -0.49838785  0.27143895  0.14436907 -0.40681301 -0.18284184
  -0.36295729  0.27723476  0.38454156  0.00130031]
 [ 0.10666942 -0.50594951 -0.26284002  0.13603618  0.32591676 -0.39295944
  -0.10978785 -0.0606051   0.39994925  0.36357032]
 [ 0.36083536 -0.00561559  0.0063346   0.10978319 -0.1052944   0.27296836
   0.14950953 -0.22251973 -0.3224356  -0.24356571]
 [ 0.10823421  0.22849487 -0.2766607  -0.45384556  0.04733467 -0.25428917
   0.34811912  0.32834508 -0.27466063  0.19892813]
 [-0.37134556 -0.35621337  0.36144566  0.47589051 -0.07946492  0.04888538
  -0.01674933  0.27288379  0.1304381  -0.46577026]
 [ 0.28439648 -0.11442481  0.47363308 -0.13771939 -0.36122101  0.49492981
   0.00201902 -0.38184869  0.10362939 -0.36339387]
 [ 0.24794578  0.11955803 -0.35306889  0.37906535 -0.36333936 -0.048589
  -0.03870133 -0.30563799  0.15312883  0.20963857]
 [ 0.01316817 -0.28105756 -0.19618354  0.39095612  0.20470132  0.1069322
   0.32473869 -0.04613192 -0.19516661 -0.32195687]
 [ 

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца (4 балла)

In [0]:
a = np.random.random((10,10))
b = np.median(a[:,:10], axis = 1)
c = np.zeros((10,10))
for i in range(0,10):
  c[i,:] = a[i,:] - b[i]
print(c)

[[-0.42485957  0.26483016  0.1817284   0.12926989  0.09778288 -0.54638998
  -0.37477555 -0.09778288 -0.24531072  0.2125161 ]
 [ 0.10170116 -0.3222001  -0.47460712 -0.19881048  0.0435863   0.38997596
  -0.0435863   0.10839998  0.2510303  -0.15391652]
 [ 0.035188    0.20771443  0.27944358  0.0794456  -0.035188   -0.23552437
   0.25171671 -0.5324026  -0.06076182 -0.48418202]
 [-0.09725193 -0.12504529 -0.05589605  0.03331868 -0.01930891  0.49183845
  -0.08362518  0.59404991  0.48079873  0.01930891]
 [-0.5718755  -0.44299304 -0.0011287  -0.54016339 -0.40522931  0.09289816
   0.0011287   0.40757071  0.20612134  0.21431885]
 [ 0.25777085  0.59509621 -0.1089572  -0.24840034  0.41855762 -0.02529741
   0.35055929 -0.08928307 -0.28319221  0.02529741]
 [ 0.14675537  0.46479212 -0.13308036 -0.19702574  0.38957919 -0.06638921
   0.5835732  -0.20518305  0.06638921 -0.11114385]
 [ 0.06419439  0.42146636 -0.0330859  -0.23176282  0.57897561 -0.02699827
   0.02699827 -0.10130123 -0.0500884   0.51028371]


5) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7. (4 балла) 

In [0]:
a = np.random.random((5,5))
b = np.amax(a, axis = 1).reshape((5,1))
c = np.amin(a, axis = 1).reshape((5,1))
a = np.append(a,b,axis = 1)
a = np.append(a,c,axis = 1)
print(a)


[[0.52999388 0.88515983 0.24049499 0.66696124 0.46431541 0.88515983
  0.24049499]
 [0.0987557  0.69973883 0.16540962 0.04279191 0.93263924 0.93263924
  0.04279191]
 [0.04878253 0.8691942  0.14752592 0.72245599 0.29992266 0.8691942
  0.04878253]
 [0.78572682 0.80712566 0.20326641 0.2393765  0.53153157 0.80712566
  0.20326641]
 [0.10570735 0.84884871 0.59921535 0.92024586 0.46077285 0.92024586
  0.10570735]]


6) Вектор чисел от 1 до 50 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  (6 баллов)

In [4]:
vector = np.arange(1,51,1)
odd = [i for i in vector if i%2 == 1 ]
even = [i for i in vector if i%2 == 0 ]
even = np.reshape(even, (5,5))
odd = np.reshape(odd, (5,5))
mult = odd@even
print(mult)
print(np.linalg.det(mult))#определитель 0 = нет отбратной

[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]
0.0


7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. (5 баллов)

In [0]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
